### ISSUE TITLE
Any plans to add 'NOT' character? 

### ISSUE THREAD

**Issue by ellizio** [Reloaded-Project/Reloaded.Memory.SigScan#11]
Hi.
It's nice to have special character to exclude bytes that are NOT EQUALS to some value

```csharp
// Should ignore signature where fourth pair of bytes is 00
int offset = scanner.FindPattern("`AB CD EF !00 12");
```

I'm ready to help to implement this

**Comment by Sewer56** [comment]
Got no plans for it myself. Next time I'll work on this code, it'll probably be porting to Rust.

You're best off forking the library, and adding a distinct set of methods with extra functionality like this.
I don't think it's possible to add this sort of functionality into the existing methods, because it'll always introduce a branch, killing performance; which is the main goal of the library.

**Comment by Sewer56** [comment]
Otherwise you can 'hack' it in by searching for all patterns, so you'd replace `!00` with a `??`, and manually check on all returned results. This sort of thing is possible in a 'wrapper' library which operates on top of this one.

**Comment by ellizio** [comment]
@Sewer56 thanks for quick reply. 

At the moment I'm already using 'hack' as a quick solution

**Comment by Sewer56** [comment]
Well, I called it a 'hack' but in the future it may be the best way to do it actually.

I expect to cache signature scan results in the future when running the Rust port with Reloaded3, so having the `NOT` character being represented as `??` reduces the amount of cache keys. If you pass a scan with a `NOT`, it could pull results featuring `??` from cache, and filter them to ones that apply.

Even in today's code, when you do a multithreaded scan, search results are reused; that sort of thing could be expanded in the future with add-in functionality of this kind.
